### PR TITLE
fix readme

### PR DESCRIPTION
**Pull request by spicybirsge**
jwt tokens are not encrypted sir, the payload is just base64 along with a secret, it can be decoded too see https://jwt.io .
Also passwords are not "Encrypted" its called hashing, in hashing it cannot be reversed unlike encryption.

### CODE REVIEW

**Comment by spicybirsge** [comment]
image

**Comment by ghost** [comment]
jwt tokens are supposed to be decoded, and usually are stored in base64.

If you can get the secret, then that's an issue. but otherwise it's fine.

**Comment by spicybirsge** [comment]
> jwt tokens are supposed to be decoded, and usually are stored in base64.
> 
> If you can get the secret, then that's an issue. but otherwise it's fine.

u seem to not understand, the thing I am pointing out is that he said tokens are encrypted with jwt, but it isn't encrypted, so I asked edited the readMe since it is inaccurate.

**Comment by ghost** [comment]
ah

**Pull request merged**
